### PR TITLE
feat: support tag_prefix cli option

### PR DESCRIPTION
**Pull request by jgrumboe**

### CODE REVIEW

**Review by gruebel — APPROVED** [review]
thanks 🥇

**Comment by gruebel** [comment]
@jgrumboe you need to run `npm run all` once and then also commit the generated files 🙂

**Comment by jgrumboe** [comment]
@gruebel Cool, lightning fast response 💯 

I don't know if I should also build and commit the `/dist` folder in my branch and to this PR?

**Comment by jgrumboe** [comment]
@gruebel Thank you for your lightning fast response 💯

**Comment by gruebel** [comment]
I don't think your change breaks the test, probably there is an issue with invoking it for a fork

**Pull request merged**
